# Establecer la imagen base
FROM node:alpine

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /provisioning-service
COPY . .
RUN yarn

ENV PORT=3001
ENV DATABASE_HOST=localhost
ENV DATABASE_PORT=5432
ENV DATABASE_USERNAME=postgres
ENV DATABASE_PASSWORD=admin
ENV DATABASE_NAME=postgres

EXPOSE 3001

# Comando para ejecutar el servicio
CMD [ "yarn", "start" ]
