# Establecer la imagen base
FROM node:alpine

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /frontend

COPY . .

RUN yarn

EXPOSE 3000

# Comando para ejecutar el servicio
CMD [ "yarn", "dev" ]
