version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

  products:
    build: ./products
    restart: always
    ports:
      - 3002:3002
    depends_on:
      - db

  provisioning:
    build: ./provisioning-service
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - db

  gateway:
    build: ./gateway
    restart: always
    ports:
      - 3003:3003
    depends_on:
      - products
      - provisioning

  frontend:
    build: ./frontend
    restart: always
    ports:
      - 80:3000
    depends_on:
      - gateway
