# Establecer la imagen base
FROM node:alpine

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /gateway

COPY . .

RUN yarn

EXPOSE 3003

# Comando para ejecutar el servicio
CMD [ "yarn", "start" ]
